# Database configuration
dbs:
  gtdb_version: "latest"  # use release220 or release 226 etc to use older versions
  type: ["diamond", "mmseqs", "blastp"]  # Available database types: diamond, mmseqs, blastp
  # Which databases to build
  build:
    repdb: 
      decontamination:
        # these parameters were optimized through a benchmark with ContScout 
        identity: 0.9
        coverage: 0.5
        cov_mode: 3
        prop_euka: 0.5
        # size_cluster: 10
    # Custom databases: uncomment and add your database entries
    # Example:
    custom:
      clust_repdb: 
        ids: resources/repdb.ids #/gpfs/projects/bsc40/current/gmutti/projects/repdb_dev/results/meta/repdb.ids
        cluster: 
          level: class
          identity: 0.9
          coverage: 0.9
      # random: 
      #   ids: resources/random_500.ids
      #   cluster: 
      #     level: phylum
      #     identity: 0.4
      #     coverage: 0.3
      # nctv: 
      #   ids: resources/nctv.ids
      #   cluster: 
      #     level: order
      #     identity: 0.8
      #     coverage: 0.8
      smalleuks: 
        ids: resources/eukas_50.ids
        cluster: 
          level: order
          identity: 0.8
          coverage: 0.8
        decontaminate:
          identity: 0.9
          coverage: 0.5
          cov_mode: 3
          prop_euka: 0.5

# If repdb is not specified and you specified to decontaminate your custom database, 
# the pipeline will still produce the repdb.fa.gz
# Right now there is no option to do that as temp because it seems complicated to manage

files: 
  clades_to_keep: "resources/clades_tokeep.txt"
  genomes_to_exclude: "resources/exclude.txt"
  new_genomes: "resources/custom_genomes_repdb.csv"
